name: Build pull request

on:
  pull_request:
    branches: [ "master", "1.0.x" , "1.1.x" , "1.2.x" , "1.3.x" ]

jobs:
  build:
    permissions:
      checks: write
      contents: read
    uses: 'connectorio/gh-actions-shared/.github/workflows/maven.yml@master'
    secrets:
      CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
      CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
    with:
      openhab: false
      server_id: sonatype-nexus-snapshots
      master_branch: 1.3.x
      deploy: true
      skip_test_publish: true